services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false
    tags:
    - 'controller.service_arguments'

  App\Action\:
    resource: '%kernel.project_dir%/src/Action/'

  App\Action\VkCallbackAction:
    arguments:
    - '@request_stack'
    - '@message_bus'
    - '@App\DeserializationHandler'
    - '@App\VkCallbackParser'
    - '@App\UserMessageTypeDetector'
    - '%env.vk_callback_token%'
    - '%env.vk_webhook_secret%'
