services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false
    tags:
    - 'serializer.normalizer'

  App\Serializer\Normalizer\:
    resource: '%kernel.project_dir%/src/Serializer/Normalizer/'


