services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  App\StreamDetector\TwitchStreamDetector:
    arguments:
    - '@GuzzleHttp\ClientInterface'
    - '%env.twitch_application_client_id%'

  GuzzleHttp\Client: ~
