services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false

  App\VkClient\:
    resource: '%kernel.project_dir%/src/VkClient/'

  App\VkClient\VkClient:
    arguments:
    - '@GuzzleHttp\ClientInterface'
    - '@App\Repository\SentMessageRepository'
    - '%env.vk_access_token%'
    - '%vk.api_version%'
    - '%vk_scripts_dir%'
