services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false

  App\VkClient\VkMessageSenderInterface:
    alias: 'App\VkClient\VkClient'

  App\VkClient\VkClient:
    arguments:
    - '@GuzzleHttp\ClientInterface'
    - '@App\Repository\SentMessageRepository'
    - '%env.vk_message_sender_access_token%'
    - '%vk.api_version%'
    - '%vk_scripts_dir%'
