parameters:
  locale: 'en'

  # map environment variables to parameters
  env.vk_access_token: '%env(VK_ACCESS_TOKEN)%'
  env.vk_message_sender_community_id: '%env(VK_MESSAGE_SENDER_COMMUNITY_ID)%'
  env.vk_message_sender_access_token: '%env(VK_MESSAGE_SENDER_ACCESS_TOKEN)%'
  env.vk_webhook_secret: '%env(VK_WEBHOOK_SECRET)%'
  env.vk_callback_token: '%env(VK_CALLBACK_TOKEN)%'
  env.twitch_watch_usernames: '%env(TWITCH_WATCH_USERNAMES)%'
  env.twitch_application_client_id: '%env(TWITCH_APPLICATION_CLIENT_ID)%'

  vk.api_version: '5.92'

  vk_scripts_dir: '%kernel.project_dir%/vkScriptTemplates'
